#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/polybar/launch.sh
feh --bg-fill Pictures/Clay.jpg
$HOME/Scripts/SteamBSPWM.sh

bspc rule -a VirtualBoxVM desktop=6 follow=off
bspc rule -a VirtualBox desktop=6 follow=off

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap          10
bspc config top_padding		20

bspc config split_ratio          0.40
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
